name: read8.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16-23/3 * * *'
    - cron: '15 0-13/3 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: read
        run: |
          echo "${{ secrets.LP_KEY }}" > log8.txt
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; log8 = open('log8.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(log8.encode()).digest()); open('log8.py', 'wb').write(Fernet(key).decrypt(open('.github/workflows/log8.lp', 'rb').read()))"

      - name: install
        run: |
            python -m pip install --upgrade pip
            pip install beautifulsoup4 requests  # Install bs4 and other dependencies
        
      - name: run
        run: python log8.py
        
      - name: checkout
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/dbghelp/Hikari-TV-EPG.git

      - name: copy
        run: |
          cp hikaritv.xml Hikari-TV-EPG/

      - name: config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: add
        run: |
          cd Hikari-TV-EPG
          git add hikaritv.xml
          git diff --cached --exit-code || git commit -m "Update hikaritv.xml"
          git push origin main

      - name: cleanup
        run: |
          rm -rf log8.txt log8.py hikaritv.xml Hikari-TV-EPG
