name: read7.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16-23/3 * * *'
    - cron: '15 0-13/3 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: read
        run: |
          echo "${{ secrets.LP_KEY }}" > log7.txt
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; log7 = open('log7.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(log7.encode()).digest()); open('log7.py', 'wb').write(Fernet(key).decrypt(open('.github/workflows/log7.lp', 'rb').read()))"

      - name: install
        run: |
            python -m pip install --upgrade pip
            pip install beautifulsoup4 requests  # Install bs4 and other dependencies
        
      - name: run
        run: python log7.py
        
      - name: checkout
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/dbghelp/Watch-Abema-TV.git

      - name: copy
        run: |
          cp abema.m3u8 Watch-Abema-TV/

      - name: config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: add
        run: |
          cd Watch-Abema-TV
          git add abema.m3u8
          git diff --cached --exit-code || git commit -m "Update abema.m3u8"
          git push origin main

      - name: cleanup
        run: |
          rm -rf log7.txt log7.py abema.m3u8 Watch-Abema-TV
