name: read.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0-23/3 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: read
        run: |
          echo "${{ secrets.LP_KEY }}" > log.txt
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; log = open('log.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(log.encode()).digest()); open('log.py', 'wb').write(Fernet(key).decrypt(open('.github/workflows/log.lp', 'rb').read()))"

      - name: run
        run: python log.py
        
      - name: checkout
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/dbghelp/test2.git

      - name: copy
        run: |
          cp mewatch.xml test2/

      - name: config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: add
        run: |
          cd test2
          git add mewatch.xml
          git commit -m "Update mewatch.xml"
          git push origin main

      - name: cleanup
        run: |
          rm -rf log.txt log.py mewatch.xml test2
