name: read6.yml

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16-23/3 * * *'
    - cron: '15 0-13/3 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: read
        run: |
          echo "${{ secrets.LP_KEY }}" > log6.txt
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; log6 = open('log6.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(log6.encode()).digest()); open('log6.py', 'wb').write(Fernet(key).decrypt(open('.github/workflows/log6.lp', 'rb').read()))"

      - name: install
        run: |
            python -m pip install --upgrade pip
            pip install beautifulsoup4 requests playwright  # Install bs4 and other dependencies
        
      - name: run
        run: python log6.py
        
      - name: checkout
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/dbghelp/TV-Tokyo-EPG.git

      - name: copy
        run: |
          cp tv_tokyo.xml TV-Tokyo-EPG/

      - name: config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: add
        run: |
          cd TV-Tokyo-EPG
          git add tv_tokyo.xml
          git diff --cached --exit-code || git commit -m "Update tv_tokyo.xml"
          git push origin main

      - name: cleanup
        run: |
          rm -rf log6.txt log6.py tv_tokyo.xml TV-Tokyo-EPG
